[versions]
agp = "8.12.0"
kotlin = "2.2.0"
#xposed-api = "master-SNAPSHOT"
xposed-api = "100"
core-version = "1.16.0"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
#libxposed-api = { group = "com.github.libxposed", name = "api", version.ref = "xposed-api" } Hopefully
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "xposed-api" }
core = { group = "androidx.core", name = "core", version.ref = "core-version" }